version: '3'
services:
  namenode:
    container_name: namenode
    hostname: namenode
    image: gradiant/hdfs-namenode
    environment:
    - CLUSTER_NAME=hdfs-cluster
    - CORE_CONF_hadoop_proxyuser_root_hosts=*
    - CORE_CONF_hadoop_proxyuser_root_groups=*
    - HDFS_CONF_dfs_permissions_superusergroup=root
    - HDFS_CONF_dfs_replication=1
    volumes:
    - name:/hadoop/dfs/name
  datanode:
    container_name: datanode
    hostname: datanode
    image: gradiant/hdfs-datanode
    environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - CORE_CONF_hadoop_proxyuser_root_hosts=*
    - CORE_CONF_hadoop_proxyuser_root_groups=*
    - HDFS_CONF_dfs_permissions_superusergroup=root
    - HDFS_CONF_dfs_replication=1
    - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    volumes:
    - data-0:/hadoop/dfs/data
volumes:
  data-0:
  name:
