version: '3'
services:
  namenode:
    image: $IMAGE_REPO:$IMAGE_TAG
    environment:
    - HDFS_CONF_dfs_replication=1
    volumes:
    - name:/hadoop/dfs
    command:
    - namenode
    ports:
    - 8020:8020
    - 50070:50070
    - 9870:9870
    networks:
    - hdfs
  datanode-0:
    image: $IMAGE_REPO:$IMAGE_TAG
    environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - HDFS_CONF_dfs_replication=1
    volumes:
    - data-0:/hadoop/dfs
    command:
    - datanode
    networks:
    - hdfs
volumes:
  data-0:
  name:

networks:
  hdfs:
